version: 2
jobs:
  build:
    docker:
      - image: previousnext/m8s:latest
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: echo 'Run your unit tests here'
      - run:
          name: Build Environment
          command: |
            M8S_ENV_SITE_NAME=${CIRCLE_BRANCH} m8s build --git-revision=${CIRCLE_SHA1} \
                      --name=${CIRCLE_BRANCH} \
                      --domains=${CIRCLE_BRANCH}.gcp.flink-solutions.de \
                      --basic-auth-user='test' \
                      --basic-auth-pass='test'
      - run:
          name: Build Step Example
          command: m8s step ${CIRCLE_BRANCH} app "echo Hello"

workflows:
  version: 2
  build:
    jobs:
      - build
